### ISSUE TITLE
Please move away from ANTLR 3

### ISSUE THREAD

**Issue by FabianWolff** [cvc5/cvc5-projects#105]
Some time ago, I reported [a bug](https://github.com/antlr/antlr3/issues/193) against ANTLR 3 that involved a licensing issue. I was subsequently informed by @timeraider4u that

> Antlr3 does not receive updates any more (last commit/release was in 2015) and all development happens now in antlr4, so I guess there will not be any changes regarding the licenses of these files.

I then had to solve the problem by reimplementing the affected functionality of libantlr3c in order to keep libantlr3c (and therefore CVC4, which depends on it) in the Debian archives, but it was an ugly solution meant only as a provisional solution.

Given that libantlr3c is effectively unmaintained and starting to show serious issues that won't get solved upstream, I would recommend the CVC4 project to move away from libantlr3c in the medium-term.

**Comment by aniemetz** [comment]
@FabianWolff @jamesjer cvc5 now does not depend on ANTLR anymore.

**Comment by jamesjer** [comment]
Thank you for the heads up.  That's great to know.  I actually took over maintainership of ANTLR3 and kept it in Fedora all this time specifically for CVC4/CVC5.  It will be good to let it go.
