### ISSUE TITLE
Internal options handling

### ISSUE THREAD

**Issue by mpreiner** [cvc5/cvc5-projects#12]
Options set via the SMT2 front-end are set **after** the theory engine is created. As a consequence, all options that are checked/used while creating/initializing the theory engine are ignored. This issue does not occur if options are set via command-line.

For example, as reported in CVC4/CVC4#2467 CVC4 segfaults when setting `bitblast=eager` via SMT2. This is because initialization of the lazy or eager solver is done while creating the BV theory solver (which is created when theory engine is created). Since the `bitblast=eager` is set afterwards, we first initialize the lazy solver. Changing the option afterwards results in a segfault since we try to access the uninitialized eager solver.

There is the method `finishInit()`, which is called when options are final and set and are safe to use. 

There are at least two ways on how to fix this:

1. Enforce that options used for initialization are only used after options are final and safe to use (finalize initialization in `finishInit()`). We will need to find a way to enforce this, i.e., throw an error if used incorrectly.
2. Delay the creation of the theory engine after all options are set.

The SMT-LIB standard also allows to set options anytime, so we have to determine options that are safe to set while solving and the ones that can only be set once at startup time and give feedback if a user tries to set an option that can't be changed after solver initialization.

**Comment by nafur** [comment]
Is this still an issue?
It seems that it is properly sorted out now: setting options is only allows until the solver is "fully initialized" (i.e. `SolverEngine::finishInit()` is called, which pretty much every function of `SolverEngine` that changes any internal state does). The only exceptions to this rule are the ones listed in the standard.

**Comment by ajreynol** [comment]
I think the internal code can (ineffectively) try to set options, see e.g. https://github.com/cvc5/cvc5/pull/8101.

This should give an error like "error: options are locked".  Is this possible?
