### ISSUE TITLE
Fatal failure for UFNRA instance at type_checker_template:51

### ISSUE THREAD

**Issue by rainoftime** [cvc5/cvc5-projects#166]
Hi,
For this formula,
[typecheckerexmp51.txt](https://github.com/CVC4/CVC4/files/4301897/typecheckerexmp51.txt)

cvc4-nightly (http://cvc4.cs.stanford.edu/downloads/builds/x86_64-linux-opt/unstable/cvc4-2020-03-07-x86_64-linux-opt) incremental mode
crashed with the information:
~~~~
Fatal failure within static CVC4::TypeNode CVC4::expr::TypeChecker::
computeType(CVC4::NodeManager*, CVC4::TNode, bool) 
at /barrett/scratch/cvc4-nightly/src/cvc4-2020-03-07
/src/expr/type_checker_template.cpp:51
Unhandled case encounteredNULL
Aborted (core dumped)
~~~~

OS: Ubuntu 16.04

**Comment by ajreynol** [comment]
No longer occurs on master.
