### ISSUE TITLE
bv proofs with type error

### ISSUE THREAD

**Issue by yoni206** [cvc5/cvc5-projects#200]
cvc4 produces a proof for which lfsc fails with a type error: "The type expected for a symbol does not match the symbol's type.".

The smt file is attached (smt.txt).
The proof is attached (plf.txt)
The output of lfsc is attached (output.txt)

To reproduce, run
`cvc4 --lang=smt2 --dump-proofs --no-bv-ineq --no-bv-algebraic --no-bv-eq smt.txt`, pipe the proof, and run lfsc on it.

This example is very big and takes a while to run.

Working on minimizing, no luck so far.

[smt.txt](https://github.com/CVC4/CVC4/files/1965647/smt.txt)
[plf.txt](https://github.com/CVC4/CVC4/files/1965648/plf.txt)
[result.txt](https://github.com/CVC4/CVC4/files/1965649/result.txt)

**Comment by ajreynol** [comment]
This issue concerns the old proof infrastructure, closing.
