### ISSUE TITLE
Move attributes and statistics out of NodeManager

### ISSUE THREAD

**Issue by 4tXJ7f** [cvc5/cvc5-projects#207]
PR https://github.com/CVC4/CVC4/pull/4682 moves the options out of the NodeManager. We will have to do the same with attributes and statistics because they can't be shared with a subsolver. Ideally, the NodeManager is purely dealing with nodes but holds absolutely no other state.

**Comment by ajreynol** [comment]
NodeManager no longer contains statistics.

Attributes *should* be used by NodeManager. In particular, attributes should be used for things that are truly global, i.e. variable names.

Conversely, attributes should not be used by things that are local to a solver. For example, the rewriter should not use attributes, especially if rewritten forms are options dependent. Instead, we should use local (non-ref-counting) maps for such purpose.

**Comment by ajreynol** [comment]
The design of NodeManager is now satisfactory in this regard.
