### ISSUE TITLE
getUnsatCore() after checkSatAssuming()

### ISSUE THREAD

**Issue by mpreiner** [cvc5/cvc5-projects#308]
cvc5/cvc5@603d211
The following test fails since getUnsatCore() returns t2, which is not correct. The unsat core should be empty in this case.
```
#include <cvc5/cvc5.h>
#include <cassert>

using namespace cvc5::api;

int main(void)
{
  Solver slv;
  slv.setOption("check-proofs", "true");
  Sort s1 = slv.getBooleanSort();
  Term t1 = slv.mkConst(s1, "_x0");
  Term t2 = slv.mkTerm(Kind::XOR, t1, t1);
  slv.checkSatAssuming({t2});
  auto unsat_core = slv.getUnsatCore();
  assert(unsat_core.empty());
}
```

**Comment by 4tXJ7f** [comment]
After an offline discussion, we have decided that the unsat core should include assumptions. Instead of changing the current behavior, we need to update the API documentation to reflect this.
