### ISSUE TITLE
Int/Real subtyping issue with simplify().

### ISSUE THREAD

**Issue by aniemetz** [cvc5/cvc5-projects#337]
cvc5/cvc5@4669bb1ab2fce322cd8e3e172e57f0aa3006e1d7
murxla/murxla@62ae7231102a03eae249644152bd89d0b8a049ff
```
#include <cvc5/cvc5.h>
#include <cassert>

using namespace cvc5::api;

int main(void)
{
  Solver slv;
  Term t = d_solver.mkTerm(SEQ_UNIT, d_solver.mkReal("3416574625719121610379268"));
  Term tt = d_solver.simplify(t);                                               
  assert(t.getSort() == tt.getSort());
}
```
Fails because `t.getSort()` is `(Seq Real)` and `tt.getSort()` is `(Seq Int)`, but should be of equal sort.

**Comment by aniemetz** [comment]
https://github.com/cvc5/cvc5/pull/7577 adds this as a unit test and adds an assertion in `cvc5::api::Solver::simplify` to catch this.

**Comment by ajreynol** [comment]
SEQ_UNIT does not handle subtyping properly in general.  This requires introducing a SEQ_UNIT_OP / SEQ_UNIT kind setup where the type is carried explicitly, analogous to SINGLETON_OP / SINGLETON.

**Comment by ajreynol** [comment]
Fixed by https://github.com/cvc5/cvc5/pull/7578.
