### ISSUE TITLE
--solve-int-as-bv error: expecting bit-vector terms of the same width

### ISSUE THREAD

**Issue by mpreiner** [cvc5/cvc5-projects#348]
cvc5/cvc5@4877909b8
murxla/murxla@92d6df2
```
(set-logic ALL)
(set-option :solve-int-as-bv 1)
(declare-const x Real)
(assert (>= 0.0 x))
(check-sat)
```

error:

```
(error "expecting bit-vector terms of the same width")
```

**Comment by yoni206** [comment]
@ajreynol :
Internally, the node it ` (>= (* (- 1) x) 0)`. The `-1` is an integer and is therefore translated to a BV. But the `x` is a real, and is left intact. And thus we are trying to construct a `bvmul` between a BV and a real.

Should we ad-hoc check whether one of the arguments to arithmetic operators is a real, and if it is, translate it to itself? Or is there something more general we can do?

**Comment by ajreynol** [comment]
yes, if arith multiply takes a real as argument, then i believe the entire preprocessing pass should fail.
