### ISSUE TITLE
Fatal failure in FullModelChecker::processBuildModel() at src/theory/quantifiers/fmf/full_model_check.cpp:481

### ISSUE THREAD

**Issue by mpreiner** [cvc5/cvc5-projects#398]
cvc5/cvc5@acba73710
murxla/murxla@a952026
```
(set-logic NRAT)
(declare-fun x (Real) Real)
(assert (ite false false (forall ((_x Real)) (= (* _x _x) (+ 0.0 (x real.pi))))))
(check-sat)
```

error:

```
Fatal failure within virtual bool cvc5::theory::quantifiers::fmcheck::FullModelChecker::processBuildModel(cvc5::theory::TheoryModel*) at src/theory/quantifiers/fmf/full_model_check.cpp:481
Check failure

 false
```

**Comment by ajreynol** [comment]
I can't reproduce this.  It now complains about the logic not using UF, which is the correct behavior on this benchmark.

**Comment by mpreiner** [comment]
Can you think of a commit since cvc5/cvc5@acba737 that might have fixed the issue?

**Comment by ajreynol** [comment]
I'm not sure what commit fixed this.  The assertion was also spurious and removed at https://github.com/cvc5/cvc5/pull/8140.
