### ISSUE TITLE
Fatal failure CDHashMap::insertAtContextLevelZero() at src/context/cdhashmap.h:408

### ISSUE THREAD

**Issue by mpreiner** [cvc5/cvc5-projects#407]
murxla/murxla@541e5f122cb4765077f42a8e7a046a68b73b4d4b
cvc5/cvc5@0f5ee6bb4a4477d40d7f6577ea0c5bac17420935

```
(set-option :global-declarations true)
(define-sort _s1 (_y2 _y2))
```

error:
```
Fatal failure within void cvc5::context::CDHashMap<Key, Data, HashFcn>::insertAtContextLevelZero(const Key&, const Data&) [with Key = std::__cxx11::basic_string<char>; Data = std::pair<std::vector<cvc5::api::Sort>, cvc5::api::Sort>; HashFcn = std::hash<std::__cxx11::basic_string<char> >] at cvc5/src/context/cdhashmap.h:408
Check failure

 d_map.find(k) == d_map.end()

Aborted (core dumped)
```

I know that the above is not valid SMT2 (minimized by ddsmt), but it should not trigger this assertion error in any case, but instead report a proper parse error. Error may be related to cvc5/cvc5#4767

**Comment by ajreynol** [comment]
I believe this is the same issue as https://github.com/cvc5/cvc5/issues/4767.

**Comment by aniemetz** [comment]
>  Error may be related to [cvc5/cvc5#4767](https://github.com/cvc5/cvc5/issues/4767)

:-)

**Comment by ajreynol** [comment]
Fixed by https://github.com/cvc5/cvc5/commit/bcf90d561a60ebce1417950fd570e95199061111. Now gives this error:
```
(error "Parse Error: proj-issue407.smt2:2.27: Unexpected token: ')'.

  (define-sort _s1 (_y2 _y2))
                             ^
")
