### ISSUE TITLE
Unexpected exception with produce-unsat-cores and global-negate.

### ISSUE THREAD

**Issue by aniemetz** [cvc5/cvc5-projects#440]
cvc5/cvc5@0f5ee6b
murxla/murxla@e5e77ae
```
TEST_F(TestApiBlackSolver, foo)
{
  Solver slv;
  slv.setLogic("QF_ALL");
  slv.setOption("global-negate", "true");
  slv.setOption("produce-unsat-cores", "true");
  Sort s1 = slv.getBooleanSort();
  Term t9 = slv.mkBoolean(true);
  Term t109 = slv.mkTerm(Kind::NOT, {t9});
  slv.checkSatAssuming({t109});
  slv.getUnsatCore();
}
```
Fails with
```
terminate called after throwing an instance of 'cvc5::api::CVC5ApiException'
  what():  Cannot get unsat core unless explicitly enabled (try --produce-unsat-cores)
Aborted (core dumped)
```
If this is intended behavior, then this should be guarded when enabling option `produce-unsat-cores`. Currently, something happens silently here.

**Comment by ajreynol** [comment]
I'm surprised by this, this should throw an option exception, see https://github.com/cvc5/cvc5/blob/master/src/smt/set_defaults.cpp#L1119
and https://github.com/cvc5/cvc5/blob/master/src/smt/set_defaults.cpp#L403.

This exception should be throw at the call to `checkSatAssuming`.
