### ISSUE TITLE
unknown(incomplete) without a counter example

### ISSUE THREAD

**Issue by XiaoLi0614** [cvc5/cvc5-projects#45]
Hi,

I'm trying to analyze dependency relations between different operations in the following cvc4 file and I got the result unknown(incomplete) without a counterexample. I'm expecting the "valid" result from cvc4. Because "addemployee" operation does not depend on "incSalary" operation. Is there anyway cvc4 can output "valid" which is a reasonable result or a counterexample for debugging purpose?
[exampleForDeps.txt](https://github.com/CVC4/CVC4/files/3673388/exampleForDeps.txt)

**Comment by ajreynol** [comment]
Note we no longer support the cvc language.
