### ISSUE TITLE
Partial function application on QF_NRA

### ISSUE THREAD

**Issue by nafur** [cvc5/cvc5-projects#450]
Found this issue
```
$ cat murxla-dd-1475297646.trace 
set-murxla-options --cvc5 --reals
43382 new
28305 set-option produce-unsat-cores true
98863 set-option produce-models true
44985 mk-sort SORT_REAL
return s1
86737 mk-const s1 "_x0"
return t1
15496 mk-term OP_REAL_ADD SORT_REAL 2 t1 t1
return t8 s1
62622 mk-term OP_DISTINCT SORT_BOOL 2 t8 t8
return t9 s2
93212 mk-var s2 "_f3_0"
return t11
93212 mk-var s1 "_f3_1"
return t12
93212 mk-var s2 "_f3_2"
return t13
93212 mk-var s1 "_f3_3"
return t14
93212 mk-fun "_f3" 4 t11 t12 t13 t14 t12
return t42 s3
37029 mk-value s1 "9974541" "938"
return t86
52937 mk-const s3 "_x8"
return t87
79856 check-sat
14963 cvc5-block-model-values 3 t8 t87 t86
79130 check-sat
```
producing the following error on cvc5 676b43d08a40b7e83002461e8a76421280f8ce4f
```
terminate called after throwing an instance of 'cvc5::api::CVC5ApiException'
  what():  Partial function applications are only supported with higher-order logic. Try adding the logic prefix HO_.
```
Note sure what to make of this, might just be fine (it is an API exception after all). Putting here to not forget about it...

**Comment by nafur** [comment]
@aniemetz @mpreiner Maybe you can have a look at this, or run your trace-to-cpp script. I have a really hard time figuring out what this is doing, and whether this exception is what we would expect...

**Comment by ajreynol** [comment]
If I understand the trace correctly, this is expected behavior.  You are blocking the model value of `t87`, which is a *function*. Note that this means that higher-order should be enabled.  We could make the exception caught earlier and be more informative, e.g. "functions are not permitted in block-model-values unless higher order is enabled".
