### ISSUE TITLE
ackermann does not fully eliminate arrays

### ISSUE THREAD

**Issue by ajreynol** [cvc5/cvc5-projects#461]
In a debug build:

```
cvc5 regress0/bv/ackermann3.smt2 --ackermann --check-unsat-cores 
```
gives:
```
(error "The logic was specified as QF_BV, which doesn't include THEORY_ARRAYS, but found a term in that theory.
You might want to extend your logic to QF_ABV
")
```

Similar behavior on `regress0/arith/integers/ackermann4.smt2`.

**Comment by yoni206** [comment]
I am not sure if Ackermannization can fully eliminate arrays.
Unlike uninterpreted functions, we may have `(= a b)` where `a` and `b` have sort `Array`. 
@4tXJ7f do we use ackermannization (or eager bit-blaster) in the competition? I only see eager bit-blasting for QF_NIA (which results in QF_BV) and QF_UFBV/QF_BV), that is, no arrays.

If this is indeed the case, I think this issue can be resolved by removing this block:
https://github.com/cvc5/cvc5/blob/427d38c14eb23026e6866ad4b2663e3d6e82399e/src/smt/set_defaults.cpp#L295

But I am wondering why we had it in the first place and how come this didn't arise long ago.

**Comment by 4tXJ7f** [comment]
I think that the proper way to deal with this is to improve the error message We can deal with this by throwing a `LogicException` when we try to create an array term in the ackermannization preprocessing pass, which says that we couldn't eliminate the term in question. However, we should first make sure that ackermannization really isn't able to solve, e.g., ackermann3. It seems to me that that should be possible?

**Comment by yoni206** [comment]
I think `ackermann3` can be solved, but just that the Ackermannized formula will still include arrays and so the logic shouldn't change.

For example, if you have `(select a i)` and `(select b j)` in your formula, you would  replace these terms by `zi` and  `zj`, respectively, and then you need to add the following consistency lemma:
`(a = b /\ i = j) ==> zi = zj`.

`a` and `b` will remain in the formula. I have confirmed this by printing the result of ackermannization on `ackermann3.smt2` -- the array variables are still there and are being used.
