### ISSUE TITLE
Open proof from nonlinear on regression

### ISSUE THREAD

**Issue by ajreynol** [cvc5/cvc5-projects#489]
`cvc5 ./regress0/nl/proj-issue-451-ran-combination-1.smt2 --dump-proofs --proof-check=eager`
gives
```
Fatal failure within void cvc5::ensureClosedWrtInternal(cvc5::Node, cvc5::ProofGenerator*, cvc5::ProofNode*, const std::vector<cvc5::NodeTemplate<true> >&, const char*, const char*, bool) at /space/ajreynol/cvc5-ajr/src/proof/proof_ensure_closed.cpp:140
Check failure

 isClosed
...ensureClosed: open proof from ProofGenerator: Proof_0 in context TheoryEngine::lemma_initial, use -t te-proof-debug for details, use -t dump-proof-error for details on proof
Abort (core dumped)
```
Lemma originates from NL

**Comment by ajreynol** [comment]
Similar issue happens on `cvc5 regress1/quantifiers/nra-interleave-inst.smt2 --dump-proofs --proof-check=eager`.

**Comment by nafur** [comment]
The reason is that this whole variable elimination by equalities business does not produce proofs yet. We should make it so, eventually, and disable it for the time being if proofs are enabled.
