### ISSUE TITLE
Migrate builtinOp in SMT2 parser to new API

### ISSUE THREAD

**Issue by 4tXJ7f** [cvc5/cvc5-projects#83]
Concerns: https://github.com/CVC4/CVC4/blob/master/src/parser/smt2/Smt2.g#L2687

This task essentially consists of mapping the existing kinds to the kinds defined by the new API: https://github.com/CVC4/CVC4/blob/master/src/api/cvc4cppkind.h

**Comment by ajreynol** [comment]
This has been completed.
